"""envio_conteudo: id_capitulo_destino + drop conteudo_docx

Revision ID: 05ad77248612
Revises: b21407691cd5
Create Date: 2026-05-24 13:00:31.386368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05ad77248612'
down_revision = 'b21407691cd5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envios_conteudo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_capitulo_destino', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'capitulos_documento', ['id_capitulo_destino'], ['id_capitulo_documento'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envios_conteudo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_capitulo_destino')

    # ### end Alembic commands ###
