"""Adicionar sugestoes_json a envios_conteudo

Revision ID: 1bc361800789
Revises: e7a1d2c3b4f5
Create Date: 2026-05-25 06:14:01.650353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc361800789'
down_revision = 'e7a1d2c3b4f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envios_conteudo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sugestoes_json', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envios_conteudo', schema=None) as batch_op:
        batch_op.drop_column('sugestoes_json')

    # ### end Alembic commands ###
