"""adicionar_token_convite_e_expiracao_senha_nullable

Revision ID: 37f925b00c6b
Revises: 616190b7a0b4
Create Date: 2026-05-21 02:46:41.438268

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37f925b00c6b'
down_revision = '616190b7a0b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('token_convite', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('token_expiracao', sa.DateTime(), nullable=True))
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('senha_hash',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.drop_column('token_expiracao')
        batch_op.drop_column('token_convite')

    # ### end Alembic commands ###
