"""Add capitulo status, responsavel, conteudo_docx, observacao

Revision ID: 4c718f6e3236
Revises: cdb6e924b37f
Create Date: 2026-05-21 18:50:00.522663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c718f6e3236'
down_revision = 'cdb6e924b37f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_usuario_responsavel', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('status_capitulo', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('conteudo_docx', sa.LargeBinary(), nullable=True))
        batch_op.add_column(sa.Column('observacao_coordenador', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'usuarios', ['id_usuario_responsavel'], ['id_usuario'])

    with op.batch_alter_table('configuracoes_numeracao', schema=None) as batch_op:
        batch_op.alter_column('id_biblioteca_formatacao_canonica',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracoes_numeracao', schema=None) as batch_op:
        batch_op.alter_column('id_biblioteca_formatacao_canonica',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('observacao_coordenador')
        batch_op.drop_column('conteudo_docx')
        batch_op.drop_column('status_capitulo')
        batch_op.drop_column('id_usuario_responsavel')

    # ### end Alembic commands ###
