"""remover_nome_de_usuario_adicionar_perfil_constraint_email_perfil_drop_perfis_usuarios_perfis

Revision ID: 616190b7a0b4
Revises: 6825e4494899
Create Date: 2026-05-21 02:32:26.912346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '616190b7a0b4'
down_revision = '6825e4494899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuarios_perfis')
    op.drop_table('perfis')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('perfil', sa.String(length=50), nullable=False, server_default='autor'))
    op.execute("UPDATE usuarios SET perfil = 'admin' WHERE nome_de_usuario = 'admin'")
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('perfil', server_default=None)
        batch_op.drop_constraint('usuarios_email_key', type_='unique')
        batch_op.drop_constraint('usuarios_nome_de_usuario_key', type_='unique')
        batch_op.create_unique_constraint('uq_email_perfil', ['email', 'perfil'])
        batch_op.drop_column('nome_de_usuario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nome_de_usuario', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.drop_constraint('uq_email_perfil', type_='unique')
        batch_op.create_unique_constraint('usuarios_nome_de_usuario_key', ['nome_de_usuario'])
        batch_op.create_unique_constraint('usuarios_email_key', ['email'])
        batch_op.drop_column('perfil')

    op.create_table('perfis',
    sa.Column('id_perfil', sa.INTEGER(), server_default=sa.text("nextval('perfis_id_perfil_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome_perfil', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ativo', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('atualizado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id_perfil', name='perfis_pkey'),
    sa.UniqueConstraint('nome_perfil', name='perfis_nome_perfil_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('usuarios_perfis',
    sa.Column('id_usuario_perfil', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_usuario', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_perfil', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('criado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('atualizado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfis.id_perfil'], name='usuarios_perfis_id_perfil_fkey'),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], name='usuarios_perfis_id_usuario_fkey'),
    sa.PrimaryKeyConstraint('id_usuario_perfil', name='usuarios_perfis_pkey')
    )
    # ### end Alembic commands ###
