"""migracao_inicial_postgresql

Revision ID: 6825e4494899
Revises: 
Create Date: 2026-05-21 01:58:26.217516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6825e4494899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bibliotecas_formatacao_canonica',
    sa.Column('id_biblioteca_formatacao_canonica', sa.Integer(), nullable=False),
    sa.Column('nome_biblioteca', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_biblioteca_formatacao_canonica')
    )
    op.create_table('dominios',
    sa.Column('id_dominio', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_dominio'),
    sa.UniqueConstraint('tipo', 'valor', name='uq_dominio_tipo_valor')
    )
    with op.batch_alter_table('dominios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dominios_tipo'), ['tipo'], unique=False)

    op.create_table('modelos_relatorio',
    sa.Column('id_modelo_relatorio', sa.Integer(), nullable=False),
    sa.Column('nome_modelo', sa.String(length=200), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_modelo_relatorio')
    )
    op.create_table('perfis',
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.Column('nome_perfil', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_perfil'),
    sa.UniqueConstraint('nome_perfil')
    )
    op.create_table('usuarios',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('nome_de_usuario', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=256), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nome_de_usuario')
    )
    op.create_table('notificacoes',
    sa.Column('id_notificacao', sa.Integer(), nullable=False),
    sa.Column('id_usuario_destino', sa.Integer(), nullable=False),
    sa.Column('tipo_notificacao', sa.String(length=50), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=False),
    sa.Column('lida', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_destino'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_notificacao')
    )
    op.create_table('registros_auditoria',
    sa.Column('id_registro_auditoria', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('acao', sa.String(length=100), nullable=False),
    sa.Column('entidade', sa.String(length=100), nullable=False),
    sa.Column('identificador_entidade', sa.String(length=100), nullable=True),
    sa.Column('detalhe', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_registro_auditoria')
    )
    op.create_table('relatorios_base',
    sa.Column('id_relatorio_base', sa.Integer(), nullable=False),
    sa.Column('id_modelo_relatorio', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('versao', sa.String(length=50), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=True),
    sa.Column('status_relatorio', sa.String(length=50), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_modelo_relatorio'], ['modelos_relatorio.id_modelo_relatorio'], ),
    sa.PrimaryKeyConstraint('id_relatorio_base')
    )
    op.create_table('usuarios_perfis',
    sa.Column('id_usuario_perfil', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_perfil', sa.Integer(), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_perfil'], ['perfis.id_perfil'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_usuario_perfil')
    )
    op.create_table('versoes_formatacao_canonica',
    sa.Column('id_versao_formatacao_canonica', sa.Integer(), nullable=False),
    sa.Column('id_biblioteca_formatacao_canonica', sa.Integer(), nullable=False),
    sa.Column('versao', sa.String(length=50), nullable=False),
    sa.Column('arquivo_dotx', sa.String(length=300), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_biblioteca_formatacao_canonica'], ['bibliotecas_formatacao_canonica.id_biblioteca_formatacao_canonica'], ),
    sa.PrimaryKeyConstraint('id_versao_formatacao_canonica')
    )
    op.create_table('configuracoes_numeracao',
    sa.Column('id_configuracao_numeracao', sa.Integer(), nullable=False),
    sa.Column('id_versao_formatacao_canonica', sa.Integer(), nullable=False),
    sa.Column('tipo_entidade', sa.String(length=50), nullable=False),
    sa.Column('estilo_docx', sa.String(length=100), nullable=True),
    sa.Column('formato_numeracao', sa.String(length=50), nullable=False),
    sa.Column('separador', sa.String(length=10), nullable=True),
    sa.Column('prefixo', sa.String(length=50), nullable=True),
    sa.Column('herdar_indice_pai', sa.Boolean(), nullable=True),
    sa.Column('reiniciar_por_capitulo', sa.Boolean(), nullable=True),
    sa.Column('ordem_configuracao', sa.Integer(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('padrao_ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_versao_formatacao_canonica'], ['versoes_formatacao_canonica.id_versao_formatacao_canonica'], ),
    sa.PrimaryKeyConstraint('id_configuracao_numeracao')
    )
    op.create_table('versoes_trabalho',
    sa.Column('id_versao_trabalho', sa.Integer(), nullable=False),
    sa.Column('id_relatorio_base', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('status_versao', sa.String(length=50), nullable=False),
    sa.Column('bloqueado', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_relatorio_base'], ['relatorios_base.id_relatorio_base'], ),
    sa.PrimaryKeyConstraint('id_versao_trabalho')
    )
    op.create_table('bloqueios',
    sa.Column('id_bloqueio', sa.Integer(), nullable=False),
    sa.Column('id_versao_trabalho', sa.Integer(), nullable=False),
    sa.Column('motivo_bloqueio', sa.Text(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_versao_trabalho'], ['versoes_trabalho.id_versao_trabalho'], ),
    sa.PrimaryKeyConstraint('id_bloqueio')
    )
    op.create_table('capitulos_documento',
    sa.Column('id_capitulo_documento', sa.Integer(), nullable=False),
    sa.Column('id_versao_trabalho', sa.Integer(), nullable=False),
    sa.Column('id_capitulo_pai', sa.Integer(), nullable=True),
    sa.Column('ordem_capitulo', sa.Integer(), nullable=False),
    sa.Column('nome_capitulo', sa.String(length=200), nullable=True),
    sa.Column('titulo_capitulo', sa.String(length=300), nullable=False),
    sa.Column('indice_capitulo', sa.String(length=50), nullable=True),
    sa.Column('nivel_capitulo', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_capitulo_pai'], ['capitulos_documento.id_capitulo_documento'], ),
    sa.ForeignKeyConstraint(['id_versao_trabalho'], ['versoes_trabalho.id_versao_trabalho'], ),
    sa.PrimaryKeyConstraint('id_capitulo_documento')
    )
    op.create_table('envios_conteudo',
    sa.Column('id_envio_conteudo', sa.Integer(), nullable=False),
    sa.Column('id_versao_trabalho', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nome_arquivo', sa.String(length=300), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.Column('status_envio', sa.String(length=50), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_versao_trabalho'], ['versoes_trabalho.id_versao_trabalho'], ),
    sa.PrimaryKeyConstraint('id_envio_conteudo')
    )
    op.create_table('revisoes',
    sa.Column('id_revisao', sa.Integer(), nullable=False),
    sa.Column('id_versao_trabalho', sa.Integer(), nullable=False),
    sa.Column('id_usuario_coordenador', sa.Integer(), nullable=False),
    sa.Column('status_revisao', sa.String(length=50), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario_coordenador'], ['usuarios.id_usuario'], ),
    sa.ForeignKeyConstraint(['id_versao_trabalho'], ['versoes_trabalho.id_versao_trabalho'], ),
    sa.PrimaryKeyConstraint('id_revisao')
    )
    op.create_table('acoes_revisao',
    sa.Column('id_acao_revisao', sa.Integer(), nullable=False),
    sa.Column('id_revisao', sa.Integer(), nullable=False),
    sa.Column('tipo_acao', sa.String(length=50), nullable=False),
    sa.Column('descricao_acao', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_revisao'], ['revisoes.id_revisao'], ),
    sa.PrimaryKeyConstraint('id_acao_revisao')
    )
    op.create_table('elementos_conteudo',
    sa.Column('id_elemento_conteudo', sa.Integer(), nullable=False),
    sa.Column('id_capitulo_documento', sa.Integer(), nullable=False),
    sa.Column('tipo_elemento', sa.String(length=50), nullable=False),
    sa.Column('ordem_elemento', sa.Integer(), nullable=False),
    sa.Column('numero_elemento', sa.Integer(), nullable=True),
    sa.Column('conteudo_original', sa.Text(), nullable=True),
    sa.Column('conteudo_processado', sa.Text(), nullable=True),
    sa.Column('propriedades_formatacao_json', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_capitulo_documento'], ['capitulos_documento.id_capitulo_documento'], ),
    sa.PrimaryKeyConstraint('id_elemento_conteudo')
    )
    op.create_table('previsualizacoes_conteudo',
    sa.Column('id_previsualizacao_conteudo', sa.Integer(), nullable=False),
    sa.Column('id_envio_conteudo', sa.Integer(), nullable=False),
    sa.Column('tipo_previsualizacao', sa.String(length=50), nullable=False),
    sa.Column('caminho_saida', sa.String(length=500), nullable=True),
    sa.Column('resultado_html', sa.Text(), nullable=True),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_envio_conteudo'], ['envios_conteudo.id_envio_conteudo'], ),
    sa.PrimaryKeyConstraint('id_previsualizacao_conteudo')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('previsualizacoes_conteudo')
    op.drop_table('elementos_conteudo')
    op.drop_table('acoes_revisao')
    op.drop_table('revisoes')
    op.drop_table('envios_conteudo')
    op.drop_table('capitulos_documento')
    op.drop_table('bloqueios')
    op.drop_table('versoes_trabalho')
    op.drop_table('configuracoes_numeracao')
    op.drop_table('versoes_formatacao_canonica')
    op.drop_table('usuarios_perfis')
    op.drop_table('relatorios_base')
    op.drop_table('registros_auditoria')
    op.drop_table('notificacoes')
    op.drop_table('usuarios')
    op.drop_table('perfis')
    op.drop_table('modelos_relatorio')
    with op.batch_alter_table('dominios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dominios_tipo'))

    op.drop_table('dominios')
    op.drop_table('bibliotecas_formatacao_canonica')
    # ### end Alembic commands ###
