"""adicionar_colunas_secao_a_capitulos

Revision ID: 971c1d36bcfa
Revises: 1bc361800789
Create Date: 2026-05-26 18:42:49.962076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971c1d36bcfa'
down_revision = '1bc361800789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_secao_inicio', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_secao_fim', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('classificacao', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('prefixo_indice', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('estilo_docx', sa.String(length=100), nullable=True))
        batch_op.drop_index('ix_cap_doc_status_capitulo_id')
        batch_op.create_index(batch_op.f('ix_capitulos_documento_status_capitulo_id'), ['status_capitulo_id'], unique=False)
        batch_op.create_foreign_key(None, 'secoes_docx', ['id_secao_inicio'], ['id_secao'])
        batch_op.create_foreign_key(None, 'secoes_docx', ['id_secao_fim'], ['id_secao'])

    with op.batch_alter_table('envios_conteudo', schema=None) as batch_op:
        batch_op.drop_index('ix_envios_status_capitulo_id')
        batch_op.drop_index('ix_envios_status_envio_id')
        batch_op.drop_index('ux_envios_por_capitulo', postgresql_where='(id_capitulo_destino IS NOT NULL)')
        batch_op.create_index(batch_op.f('ix_envios_conteudo_status_capitulo_id'), ['status_capitulo_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_envios_conteudo_status_envio_id'), ['status_envio_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envios_conteudo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_envios_conteudo_status_envio_id'))
        batch_op.drop_index(batch_op.f('ix_envios_conteudo_status_capitulo_id'))
        batch_op.create_index('ux_envios_por_capitulo', ['id_relatorio', 'id_capitulo_destino'], unique=True, postgresql_where='(id_capitulo_destino IS NOT NULL)')
        batch_op.create_index('ix_envios_status_envio_id', ['status_envio_id'], unique=False)
        batch_op.create_index('ix_envios_status_capitulo_id', ['status_capitulo_id'], unique=False)

    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_capitulos_documento_status_capitulo_id'))
        batch_op.create_index('ix_cap_doc_status_capitulo_id', ['status_capitulo_id'], unique=False)
        batch_op.drop_column('estilo_docx')
        batch_op.drop_column('prefixo_indice')
        batch_op.drop_column('classificacao')
        batch_op.drop_column('id_secao_fim')
        batch_op.drop_column('id_secao_inicio')

    # ### end Alembic commands ###
