"""add caminho_arquivo to relatorios_finalizados

Revision ID: 985f72ee2822
Revises: 9c57f33cb133
Create Date: 2026-05-22 11:04:06.216420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '985f72ee2822'
down_revision = '9c57f33cb133'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios_finalizados', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caminho_arquivo', sa.String(length=500), nullable=True))
        batch_op.alter_column('snapshot_conteudo',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=True)
        batch_op.alter_column('artefato_docx',
               existing_type=postgresql.BYTEA(),
               nullable=True)
        batch_op.alter_column('nome_arquivo',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('relatorios_finalizados', schema=None) as batch_op:
        batch_op.alter_column('nome_arquivo',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.alter_column('artefato_docx',
               existing_type=postgresql.BYTEA(),
               nullable=False)
        batch_op.alter_column('snapshot_conteudo',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               nullable=False)
        batch_op.drop_column('caminho_arquivo')

    # ### end Alembic commands ###
