"""Ajustar campos de classificação em CapituloDocumento: prefixo_indice String(20)->String(10), adicionar comentários

Revision ID: 98dbc83e450f
Revises: 971c1d36bcfa
Create Date: 2026-05-26 20:29:17.441006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98dbc83e450f'
down_revision = '971c1d36bcfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.alter_column('id_secao_inicio',
               existing_type=sa.INTEGER(),
               comment='ID da seção DOCX onde o capítulo começa',
               existing_nullable=True)
        batch_op.alter_column('id_secao_fim',
               existing_type=sa.INTEGER(),
               comment='ID da seção DOCX onde o capítulo termina (se abrange múltiplas seções)',
               existing_nullable=True)
        batch_op.alter_column('tipo_elemento',
               existing_type=sa.VARCHAR(length=50),
               comment='Tipo de elemento: pre_textual, textual, pos_textual',
               existing_nullable=False)
        batch_op.alter_column('classificacao',
               existing_type=sa.VARCHAR(length=50),
               comment='Classificação do capítulo: textual, pre_textual, pos_textual, anexo, apendice',
               existing_nullable=True)
        batch_op.alter_column('prefixo_indice',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=10),
               comment="Prefixo de numeração (ex: 'I', '1', 'A')",
               existing_nullable=True)
        batch_op.alter_column('estilo_docx',
               existing_type=sa.VARCHAR(length=100),
               comment="Estilo DOCX do título (ex: 'Heading 1', 'Título 1')",
               existing_nullable=True)
        batch_op.alter_column('docx_bookmark',
               existing_type=sa.VARCHAR(length=200),
               comment='Marcador (bookmark) no DOCX para referências cruzadas',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.alter_column('docx_bookmark',
               existing_type=sa.VARCHAR(length=200),
               comment=None,
               existing_comment='Marcador (bookmark) no DOCX para referências cruzadas',
               existing_nullable=True)
        batch_op.alter_column('estilo_docx',
               existing_type=sa.VARCHAR(length=100),
               comment=None,
               existing_comment="Estilo DOCX do título (ex: 'Heading 1', 'Título 1')",
               existing_nullable=True)
        batch_op.alter_column('prefixo_indice',
               existing_type=sa.String(length=10),
               type_=sa.VARCHAR(length=20),
               comment=None,
               existing_comment="Prefixo de numeração (ex: 'I', '1', 'A')",
               existing_nullable=True)
        batch_op.alter_column('classificacao',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Classificação do capítulo: textual, pre_textual, pos_textual, anexo, apendice',
               existing_nullable=True)
        batch_op.alter_column('tipo_elemento',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Tipo de elemento: pre_textual, textual, pos_textual',
               existing_nullable=False)
        batch_op.alter_column('id_secao_fim',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID da seção DOCX onde o capítulo termina (se abrange múltiplas seções)',
               existing_nullable=True)
        batch_op.alter_column('id_secao_inicio',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID da seção DOCX onde o capítulo começa',
               existing_nullable=True)

    # ### end Alembic commands ###
