"""add caminho_template to relatorios_producao

Revision ID: 9c57f33cb133
Revises: 4c718f6e3236
Create Date: 2026-05-22 10:48:19.062412

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9c57f33cb133'
down_revision = '4c718f6e3236'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relatorios_base',
    sa.Column('id_relatorio_base', sa.Integer(), nullable=False),
    sa.Column('id_modelo_relatorio', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=300), nullable=False),
    sa.Column('versao', sa.String(length=50), nullable=True),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=True),
    sa.Column('status_relatorio', sa.String(length=50), nullable=False),
    sa.Column('criado_por', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.Column('atualizado_por', sa.Integer(), nullable=True),
    sa.Column('atualizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_modelo_relatorio'], ['modelos_relatorio.id_modelo_relatorio'], ),
    sa.PrimaryKeyConstraint('id_relatorio_base')
    )
    with op.batch_alter_table('dom_perfis_usuario', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('dom_status_relatorios', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('relatorios_finalizados', schema=None) as batch_op:
        batch_op.alter_column('snapshot_conteudo',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('data_finalizacao',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('sincronizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('relatorios_producao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('caminho_template', sa.String(length=500), nullable=True))
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.drop_constraint('relatorios_producao_codigo_d20_numero_medicao_key', type_='unique')

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('email_verificado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('token_expiracao',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('criado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('atualizado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('desativado_em',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.alter_column('desativado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('atualizado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('token_expiracao',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('email_verificado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)

    with op.batch_alter_table('relatorios_producao', schema=None) as batch_op:
        batch_op.create_unique_constraint('relatorios_producao_codigo_d20_numero_medicao_key', ['codigo_d20', 'numero_medicao'])
        batch_op.alter_column('atualizado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.drop_column('caminho_template')

    with op.batch_alter_table('relatorios_finalizados', schema=None) as batch_op:
        batch_op.alter_column('sincronizado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('data_finalizacao',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('snapshot_conteudo',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)

    with op.batch_alter_table('dom_status_relatorios', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('dom_perfis_usuario', schema=None) as batch_op:
        batch_op.alter_column('criado_em',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    op.drop_table('relatorios_base')
    # ### end Alembic commands ###
