"""add_docx_bookmark_to_capitulos

Revision ID: b21407691cd5
Revises: d8f92fc8a9cc
Create Date: 2026-05-23 16:11:52.158569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b21407691cd5'
down_revision = 'd8f92fc8a9cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('docx_bookmark', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.drop_column('docx_bookmark')

    # ### end Alembic commands ###
