"""add id_versao_formatacao_canonica to versoes_trabalho

Revision ID: b326b9f0e71c
Revises: 37f925b00c6b
Create Date: 2026-05-21 16:03:50.232899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b326b9f0e71c'
down_revision = '37f925b00c6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versoes_trabalho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_versao_formatacao_canonica', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'versoes_formatacao_canonica', ['id_versao_formatacao_canonica'], ['id_versao_formatacao_canonica'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versoes_trabalho', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_versao_formatacao_canonica')

    # ### end Alembic commands ###
