"""consolidate biblioteca formatacao remove versoes table

Revision ID: cdb6e924b37f
Revises: b326b9f0e71c
Create Date: 2026-05-21 16:26:47.153452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cdb6e924b37f'
down_revision = 'b326b9f0e71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bibliotecas_formatacao_canonica', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivo_docx', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('caminho_arquivo', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('extraida', sa.Boolean(), nullable=True))

    with op.batch_alter_table('configuracoes_numeracao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_biblioteca_formatacao_canonica', sa.Integer(), nullable=True))
        batch_op.drop_constraint('configuracoes_numeracao_id_versao_formatacao_canonica_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bibliotecas_formatacao_canonica', ['id_biblioteca_formatacao_canonica'], ['id_biblioteca_formatacao_canonica'])
        batch_op.drop_column('id_versao_formatacao_canonica')

    with op.batch_alter_table('versoes_trabalho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_biblioteca_formatacao_canonica', sa.Integer(), nullable=True))
        batch_op.drop_constraint('versoes_trabalho_id_versao_formatacao_canonica_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'bibliotecas_formatacao_canonica', ['id_biblioteca_formatacao_canonica'], ['id_biblioteca_formatacao_canonica'])
        batch_op.drop_column('id_versao_formatacao_canonica')

    op.drop_table('versoes_formatacao_canonica')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('versoes_trabalho', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_versao_formatacao_canonica', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('versoes_trabalho_id_versao_formatacao_canonica_fkey', 'versoes_formatacao_canonica', ['id_versao_formatacao_canonica'], ['id_versao_formatacao_canonica'])
        batch_op.drop_column('id_biblioteca_formatacao_canonica')

    with op.batch_alter_table('configuracoes_numeracao', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_versao_formatacao_canonica', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('configuracoes_numeracao_id_versao_formatacao_canonica_fkey', 'versoes_formatacao_canonica', ['id_versao_formatacao_canonica'], ['id_versao_formatacao_canonica'])
        batch_op.drop_column('id_biblioteca_formatacao_canonica')

    with op.batch_alter_table('bibliotecas_formatacao_canonica', schema=None) as batch_op:
        batch_op.drop_column('extraida')
        batch_op.drop_column('caminho_arquivo')
        batch_op.drop_column('arquivo_docx')

    op.create_table('versoes_formatacao_canonica',
    sa.Column('id_versao_formatacao_canonica', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('id_biblioteca_formatacao_canonica', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('versao', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('arquivo_dotx', sa.VARCHAR(length=300), autoincrement=False, nullable=True),
    sa.Column('caminho_arquivo', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('ativa', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('criado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('criado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('atualizado_por', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('atualizado_em', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_biblioteca_formatacao_canonica'], ['bibliotecas_formatacao_canonica.id_biblioteca_formatacao_canonica'], name='versoes_formatacao_canonica_id_biblioteca_formatacao_canon_fkey'),
    sa.PrimaryKeyConstraint('id_versao_formatacao_canonica', name='versoes_formatacao_canonica_pkey')
    )
    # ### end Alembic commands ###
