"""add_tipo_elemento_to_capitulos

Revision ID: d8f92fc8a9cc
Revises: add_em_producao_status
Create Date: 2026-05-23 16:11:26.675428

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8f92fc8a9cc'
down_revision = 'add_em_producao_status'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_elemento', sa.String(length=50), nullable=True))

    # Atualizar registros existentes com valor padrão
    op.execute("UPDATE capitulos_documento SET tipo_elemento = 'textual' WHERE tipo_elemento IS NULL")

    # Agora tornar NOT NULL
    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.alter_column('tipo_elemento', nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.drop_column('tipo_elemento')

    # ### end Alembic commands ###
