"""Adicionar indice_esperado em CapituloDocumento para suporte a match por contexto

Revision ID: ea6299c23dd5
Revises: 98dbc83e450f
Create Date: 2026-05-27 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6299c23dd5'
down_revision = '98dbc83e450f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.add_column(sa.Column('indice_esperado', sa.Integer(), nullable=True, comment='Índice esperado do capítulo para match por contexto (ex: 5 para capítulo 5)'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('capitulos_documento', schema=None) as batch_op:
        batch_op.drop_column('indice_esperado')

    # ### end Alembic commands ###