"""make relatorio_id nullable in relatorios_finalizados

Revision ID: make_relatorio_id_nullable
Revises: 985f72ee2822
Create Date: 2026-05-22 18:00:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'make_relatorio_id_nullable'
down_revision = '985f72ee2822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'relatorios_finalizados', schema=None
    ) as batch_op:
        batch_op.alter_column(
            'relatorio_id',
            existing_type=sa.Integer(),
            nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        'relatorios_finalizados', schema=None
    ) as batch_op:
        batch_op.alter_column(
            'relatorio_id',
            existing_type=sa.Integer(),
            nullable=False
        )

    # ### end Alembic commands ###
